#!/bin/bash

# Update /etc/hosts to map localhost to 127.0.0.2
sudo sed -i 's/^127.0.0.1\s\+localhost$/127.0.0.1\tlocalhost\n127.0.0.2\tlocalhost/' /etc/hosts

# Update /etc/resolv.conf to use 8.8.8.8 as the nameserver for facebook.com
sudo sed -i 's/^nameserver\s\+[0-9]\+\.[0-9]\+\.[0-9]\+\.[0-9]\+$/nameserver 8.8.8.8\nnameserver &/' /etc/resolv.conf
