#!/usr/bin/env bash

# Get the list of all network interfaces
interfaces=$(ifconfig -s | awk '{print $1}' | tail -n +2)

# Loop through each interface and get its IP addresses
for i in $interfaces; do
    ips=$(ifconfig $i | grep 'inet ' | awk '{print $2}')
    for ip in $ips; do
        # Only show IPv4 addresses
        if [[ $ip == *"."* ]]; then
            echo "$i: $ip"
        fi
    done
done
